export default [
  {
    review_id: 1,
    'sound quality': 4.5,
    durable: 4.0,
    issues: 2.5,
  },
  {
    review_id: 2,
    'battery life': 5.0,
    seamless: 5.0,
    comfortable: 5.0,
    feature: 5.0,
  },
  {
    review_id: 3,
    fit: 3.0,
    experience: 2.8,
  },
  {
    review_id: 4,
    functionality: 4.2,
    issues: 3.5,
  },
  {
    review_id: 5,
    convenient: 5.0,
    durable: 5.0,
    bass: 4.9,
    fit: 5.0,
  },
  {
    review_id: 6,
    price: 2.0,
    issues: 2.0,
    feature: 2.5,
  },
  {
    review_id: 7,
    'sound quality': 5.0,
    effective: 4.8,
    upgrade: 4.7,
  },
  {
    review_id: 8,
    'fall out': 3.0,
    quality: 3.8,
  },
  {
    review_id: 9,
    functionality: 4.8,
    seamless: 4.7,
    bass: 4.6,
  },
  {
    review_id: 10,
    upgrade: 5.0,
    'value for money': 5.0,
    feature: 5.0,
    'sound quality': 5.0,
  },
  {
    review_id: 11,
    'sound quality': 4.7,
    comfortable: 3.5,
    durable: 4.5,
  },
  {
    review_id: 12,
    'fall out': 2.0,
    price: 2.5,
    issues: 2.0,
  },
  {
    review_id: 13,
    'battery life': 5.0,
    fit: 4.9,
    functionality: 5.0,
  },
  {
    review_id: 14,
    'sound quality': 4.0,
    durable: 2.5,
    feature: 3.8,
  },
  {
    review_id: 15,
    'noise canceling': 4.5,
    price: 3.5,
    functionality: 4.7,
  },
  {
    review_id: 16,
    'sound quality': 5.0,
    fit: 5.0,
    seamless: 5.0,
  },
  {
    review_id: 17,
    price: 2.5,
    'sound quality': 4.0,
    issues: 3.0,
  },
  {
    review_id: 18,
    performance: 4.0,
    issues: 3.5,
    'ease of use': 4.2,
  },
  {
    review_id: 19,
    'noise canceling': 5.0,
    feature: 5.0,
    durable: 4.9,
  },
  {
    review_id: 20,
    'sound quality': 4.5,
    comfortable: 3.0,
  },
];
