export default [
  {
    id: 1,
    rating: 4.5,
    title: 'Great sound quality, but pricey',
    comment:
      'The sound is amazing, but I wish they were a bit cheaper. Noise canceling works wonders though!',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'John D',
    timestamp: 1694565600,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 35,
  },
  {
    id: 2,
    rating: 5.0,
    title: 'Best purchase ever!',
    comment:
      'Absolutely love these AirPods! Worth every penny. The battery life is solid and the noise cancellation is superb.',
    images: ['image1.jpg', 'image2.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Sarah K',
    timestamp: 1694569200,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 20,
  },
  {
    id: 3,
    rating: 3.0,
    title: 'Not comfortable for long wear',
    comment:
      "The sound quality is good, but I can't wear them for long periods without discomfort.",
    images: ['image3.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Alex M',
    timestamp: 1694572800,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 12,
  },
  {
    id: 4,
    rating: 4.0,
    title: 'Decent performance, minor issues',
    comment:
      'Overall great product, but I experienced occasional connection drops.',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Linda P',
    timestamp: 1694576400,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 18,
  },
  {
    id: 5,
    rating: 5.0,
    title: 'Perfect for working out',
    comment:
      'Stays in place during workouts and the sound quality is top-notch!',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'David R',
    timestamp: 1694580000,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 25,
  },
  {
    id: 6,
    rating: 2.5,
    title: 'Overhyped and overpriced',
    comment:
      'These are okay, but I feel like there are cheaper alternatives that perform just as well.',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Emily H',
    timestamp: 1694583600,
    verified_purchase: false,
    vine_reviewer: true,
    helpful_vote: 5,
  },
  {
    id: 7,
    rating: 4.8,
    title: 'Fantastic noise canceling!',
    comment:
      'I use these every day on my commute and they block out all the noise. Best investment for travel!',
    images: ['image4.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Michael L',
    timestamp: 1694587200,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 30,
  },
  {
    id: 8,
    rating: 3.5,
    title: 'Decent product, but expected more',
    comment:
      "They're good, but not as groundbreaking as I expected. Noise canceling is good, but the fit could be better.",
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Olivia N',
    timestamp: 1694590800,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 10,
  },
  {
    id: 9,
    rating: 4.7,
    title: 'Excellent for calls and music',
    comment:
      'Perfect for taking calls and listening to music. The mic quality is really clear.',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Chris T',
    timestamp: 1694594400,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 22,
  },
  {
    id: 10,
    rating: 5.0,
    title: 'Amazing product, highly recommend',
    comment:
      "I don't know how I lived without these before. The sound quality is fantastic and the transparency mode is a game-changer.",
    images: ['image5.jpg', 'image6.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Sophie B',
    timestamp: 1694598000,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 40,
  },
  {
    id: 11,
    rating: 4.7,
    title: 'Amazing sound, but could be more comfortable',
    comment:
      'The sound quality is excellent, but after long use, my ears get sore. Still, a great product overall!',
    images: ['image7.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Mark S',
    timestamp: 1694601600,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 17,
  },
  {
    id: 12,
    rating: 2.5,
    title: 'Not worth the money',
    comment:
      'I had high expectations, but they fell out too often, and the price is just too high for what they offer.',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Ashley T',
    timestamp: 1694605200,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 8,
  },
  {
    id: 13,
    rating: 4.9,
    title: 'Excellent for daily use',
    comment:
      'The battery life is incredible, and the fit is perfect for my workouts. Highly recommend!',
    images: ['image8.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Brian W',
    timestamp: 1694608800,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 26,
  },
  {
    id: 14,
    rating: 3.7,
    title: 'Good but not durable',
    comment:
      'The sound and features are great, but one earbud stopped working after just a month. Disappointed in the durability.',
    images: ['image9.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Erica L',
    timestamp: 1694612400,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 13,
  },
  {
    id: 15,
    rating: 4.2,
    title: 'Great for commuting',
    comment:
      'I use these every day on the subway. Noise-canceling is a lifesaver, though the price is a bit steep.',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Tom G',
    timestamp: 1694616000,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 18,
  },
  {
    id: 16,
    rating: 5.0,
    title: 'Simply the best earbuds',
    comment:
      'These AirPods are amazing! The fit is perfect, and the sound quality is unmatched.',
    images: ['image10.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Jenny C',
    timestamp: 1694619600,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 35,
  },
  {
    id: 17,
    rating: 2.8,
    title: 'Too expensive for what it offers',
    comment:
      "They sound good, but I don't think they justify the high price tag. There are cheaper alternatives.",
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Matthew J',
    timestamp: 1694623200,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 10,
  },
  {
    id: 18,
    rating: 4.0,
    title: 'Solid performance',
    comment:
      "I've been using them for months now, and they're reliable. The only downside is occasional connectivity issues.",
    images: ['image11.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Emily R',
    timestamp: 1694626800,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 14,
  },
  {
    id: 19,
    rating: 5.0,
    title: 'Perfect for travel',
    comment:
      "I can't live without these on long flights. The noise cancellation is unbelievable!",
    images: ['image12.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Luke P',
    timestamp: 1694630400,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 28,
  },
  {
    id: 20,
    rating: 3.5,
    title: 'Good product but uncomfortable',
    comment:
      "The sound and features are excellent, but I can't wear them for too long. They start to hurt my ears.",
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Natalie B',
    timestamp: 1694634000,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 9,
  },
];
