export default [
  {
    id: 1,
    rating: 4.5,
    title: 'Great sound quality, but pricey',
    comment:
      'The sound is amazing, but I wish they were a bit cheaper. Noise canceling works wonders though!',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'John D',
    timestamp: 1694565600,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 35,
  },
  {
    id: 2,
    rating: 5.0,
    title: 'Best purchase ever!',
    comment:
      'Absolutely love these AirPods! Worth every penny. The battery life is solid and the noise cancellation is superb.',
    images: ['image1.jpg', 'image2.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Sarah K',
    timestamp: 1694569200,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 20,
  },
  {
    id: 3,
    rating: 3.0,
    title: 'Not comfortable for long wear',
    comment:
      "The sound quality is good, but I can't wear them for long periods without discomfort.",
    images: ['image3.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Alex M',
    timestamp: 1694572800,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 12,
  },
  {
    id: 4,
    rating: 4.0,
    title: 'Decent performance, minor issues',
    comment:
      'Overall great product, but I experienced occasional connection drops.',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Linda P',
    timestamp: 1694576400,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 18,
  },
  {
    id: 5,
    rating: 5.0,
    title: 'Perfect for working out',
    comment:
      'Stays in place during workouts and the sound quality is top-notch!',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'David R',
    timestamp: 1694580000,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 25,
  },
  {
    id: 6,
    rating: 2.5,
    title: 'Overhyped and overpriced',
    comment:
      'These are okay, but I feel like there are cheaper alternatives that perform just as well.',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Emily H',
    timestamp: 1694583600,
    verified_purchase: false,
    vine_reviewer: true,
    helpful_vote: 5,
  },
  {
    id: 7,
    rating: 4.8,
    title: 'Fantastic noise canceling!',
    comment:
      'I use these every day on my commute and they block out all the noise. Best investment for travel!',
    images: ['image4.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Michael L',
    timestamp: 1694587200,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 30,
  },
  {
    id: 8,
    rating: 3.5,
    title: 'Decent product, but expected more',
    comment:
      "They're good, but not as groundbreaking as I expected. Noise canceling is good, but the fit could be better.",
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Olivia N',
    timestamp: 1694590800,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 10,
  },
  {
    id: 9,
    rating: 4.7,
    title: 'Excellent for calls and music',
    comment:
      'Perfect for taking calls and listening to music. The mic quality is really clear.',
    images: [],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Chris T',
    timestamp: 1694594400,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 22,
  },
  {
    id: 10,
    rating: 5.0,
    title: 'Amazing product, highly recommend',
    comment:
      "I don't know how I lived without these before. The sound quality is fantastic and the transparency mode is a game-changer.",
    images: ['image5.jpg', 'image6.jpg'],
    asin: 'B07ZPC9QD4',
    parent_asin: 'B07ZPC9QD4',
    user_name: 'Sophie B',
    timestamp: 1694598000,
    verified_purchase: true,
    vine_reviewer: false,
    helpful_vote: 40,
  },
];
